bank_/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'bank_.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^product/', include('product.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'product.views.home',name="home_page"),
    url(r'^logout/$', 'login.views.logout',name="logout"),
    url(r'^member/$', 'bank_.views.member',name="member"),
    url(r'^cart/$','order.views.cart',name="cart"),
    url(r'^checkout/$','order.views.order_from_cart',name="checkout"),
    url(r'^history/$','order.views.order_list',name="history"),
    url(r'^pos/$','order.views.pos',name="pos"),
    url(r'^pay/$','order.views.pay',name="pay"),
    url(r'^order/$','order.views.get_order',name="get_order"),
    url(r'^ship/$','order.views.ship',name="ship"),
          
]

login/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   url(r'^$', 'login.views.home', name='home'),
   url(r'^loged/$', 'login.views.after_lock_in',name="after_lock_in"),
   url('', include('social.apps.django_app.urls', namespace='social')),
   url('', include('django.contrib.auth.urls', namespace='auth')),
   
)

templates/thirdauth/home.html
{% extends 'base.html' %}
{% block title %}MAP SHOP{% endblock %}
{% block content %}

  <h1>Please Login</h1>
  {% if user and not user.is_anonymous %}

    
    <a>Hello {{ user.get_full_name|default:user.username }}!</a>
    <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
  {% else %}
	<a href="{% url 'social:begin' 'facebook' %}" class="btn btn-primary" role="button">FB</a>
  {% endif %}

{% endblock %}

templates/thirdauth/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>HOME</title>
</head>
<body>
  <h1>Home</h1>
  {% if user and not user.is_anonymous %}

    <a>Hello {{ user.get_full_name|default:user.username }}!</a>
    <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
  {% else %}
    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"> Login</a>
  {% endif %}
</body>
</html>

templates/thirdauth/loged.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Facebook Login</title>
</head>
<body>
    <h1>Please Wait</h1>
    
    <script type="text/javascript">
      window.location.href = "/"
    </script>
</body>
</html>

templates/thirdauth/relog.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Facebook Login</title>
</head>
<body>
    <h1>Please Wait</h1>
    
    <script type="text/javascript">
      window.location.href = "/loged"
    </script>
</body>
</html>